#!/usr/bin/python
# Create celebs.js from a list of celebrities
# Usage: make_celebs.py <input_file>

# TODO: merge this with the other generator script
import sys
if len(sys.argv) != 2:
  sys.exit("Usage: make_celebs.py <input_file>")

try:
  f_in = open(sys.argv[1], "r")
  f_out = open("celebs.js", "a")
except:
  sys.exit("Can't find file")

f_out.write("// This file is automatically generated by make_celebs.py\n")
f_out.write("let celebs = {\n")
for l in f_in.readlines():
  l = l.strip().lower().replace("\"", "")
  f_out.write("  \"%s\" : true,\n" % (l))
f_out.write("};\n")
f_out.write("module.exports = celebs;\n")
f_out.close()
f_in.close()
