#!/usr/bin/python
# Create celebs.js from a list of celebrities
# Usage: make_celebs.py <input_file> <category>

# TODO: unify these or something
import sys
if len(sys.argv) != 2:
  sys.exit("Usage: make_celebs.py <input_file>")

try:
  f_in = open(sys.argv[1], "r")
  f_out = open("celebs.js", "a")
except:
  sys.exit("Can't find file")

f_out.write("// This file is automatically generated by make_celebs.py\n")
f_out.write("let celebsRegex = /")
lines = map(lambda l : l.strip().lower().replace(" ", "\+").replace(".", "\."), f_in.readlines())
f_out.write("|".join(lines))
f_out.write("/i;\n");
f_out.write("module.exports = celebsRegex;\n")

f_out.close()
